### ISSUE TITLE
Duplicate the current line or selected lines

### ISSUE THREAD

**Issue by NomarCub** [argenos/hotkeysplus-obsidian#8] opened 2020-11-18 23:15 UTC
I already have it implemented, ready for a pull request.

**Comment by NomarCub** [comment] 2020-12-03 14:54
Would you also bump the version number for this and make a new release?

**Comment by argenos** [comment] 2020-12-04 14:33
@NomarCub I wanted to test this out before making a new release. During tests for me it duplicates the line above cursor and the duplication of selected text also had some issues. Could you let me know if there are some edge cases for this? 

![Peek 2020-12-04 15-32](https://user-images.githubusercontent.com/5426039/101175854-fcfcc780-3645-11eb-9692-979f7b2d0121.gif)

**Comment by NomarCub** [comment] 2020-12-04 15:50
Your GIF is the way I intended. I didn't do any robust testing, but it worked well for what I tried.
I intentionally worded it duplicate line(s), not duplicate selection. I know IDEs that do duplicate selection, but I went with this, because it's more intuitive to me and some programmer friends I asked.
Does it also have deviances from what I described?

**Comment by argenos** [comment] 2020-12-04 16:17
@NomarCub The command does say "Duplicate the current line or selected lines". The *current* line should be the one with the cursor instead of the line above. 

I'm not sure what would be the difference between duplicate lines vs duplicate selected lines?

**Comment by argenos** [comment] 2020-12-04 16:29
On the GIF I also noticed a small bug, where the full selection would change (the second bullet is not duplicated), and with some more testing I believe it's related to how far the selection goes on the second line. This one gets duplicated correctly: 

![image](https://user-images.githubusercontent.com/5426039/101188575-32111600-3656-11eb-9b14-ec52a89e7fb7.png)

**Comment by NomarCub** [comment] 2020-12-04 20:12
I meant the difference between selecting whole lines and parts of lines.
I wanted to avoid this.
![](https://user-images.githubusercontent.com/5298006/101209825-bc687280-3674-11eb-81ab-dcbecb823b7c.gif)
But I see that is probably not what you meant by things behaving funnily.

Now I get what you mean.
But I can see in the GIF that the cursor jumps before the duplication, because of opening the command menu. The modified selection gets duplicated correctly from what I can see.

**Comment by argenos** [comment] 2020-12-05 18:09
@NomarCub yeah, but the cursor in the selection shouldn't jump while I'm in the quick switcher. If this is what you expected, I think I can bump the version as once the `current line` fix is in.

**Comment by NomarCub** [comment] 2020-12-05 19:11
OK. I don't use the quick switcher for this command, so this didn't happen with me. And the people requesting this on forums also wanted a hotkey specifically, so I don't think this would affect most people. I wouldn't mind publishing something that is buggy because of the app, but your call.

Is this fix you mention something that the devs said they're working on?

**Comment by argenos** [comment] 2020-12-05 20:08
Sorry, I wasn't clear enough. I was referring to the "current line" of your command not being the one with the cursor. If you make a PR for it, I'll merge it and bump the version.

**Comment by NomarCub** [comment] 2020-12-05 20:25
So not the selection one? OK. Can you help me with specifics to reproduce the bug? I tried doing the things on the GIF but there's no bug for me. I'm on version 0.9.17 on Windows if that matters.
It might be the same thing as the selected lines duplication, meaning the cursor jumping because of the quick switcher, right before the duplication. Can you check if the cursor jumps like this for you regardless of this plugin?

**Comment by argenos** [comment] 2020-12-06 10:51
I’m in Ubuntu 18.04, and using the insider version so there might be differences because of that. I’m not sure if I can downgrade for a specific vault, but I’ll give it a try tomorrow. 

For all the other hotkeys I don’t recall having a problem if I trigger them throughout the command palette, but I’ll also double check that.

**Comment by NomarCub** [comment] 2021-01-09 21:04
Does it work properly with the newer Obsidian versions? Or do you have a way for me to reproduce the bug myself? I'd like to help resolve this, but there's nothing I could go on right now.

**Comment by argenos** [comment] 2021-01-11 09:50
No, unfortunately, this is still happening with v 0.10.7. I haven't had 
time to investigate why this is not reproducible to you, but I'll just 
make the release and tag you in any bug reports that come related to this.

**Comment by argenos** [comment] 2021-01-16 17:51
Sorry for the delay, I just released 0.2.3 with the changes! Hopefully, it works for those interested in using it!

**Closed by argenos** 2021-01-16 17:51 UTC
